# Initial maintaner's setup:
# 1. Create a [DockerHub personal access token](https://docs.docker.com/docker-hub/access-tokens/)
# 2. Set [Github actions repository secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository)
#    `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`
#    with values of your Docker hub username and the personal token respectively.
# 3. Replace the user tag in the "Build and push" action with your Docker hub user.

name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ozmoroz/ffiiitc:latest
